/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoInfoItem: typeof import('./src/components/common/AutoInfoItem.vue')['default']
    AutoInfoTimingItem: typeof import('./src/components/common/AutoInfoTimingItem.vue')['default']
    Card: typeof import('./src/components/common/Card.vue')['default']
    CardSecond: typeof import('./src/components/common/CardSecond.vue')['default']
    ConditionOperation: typeof import('./src/components/common/ConditionOperation.vue')['default']
    Empty: typeof import('./src/components/common/Empty.vue')['default']
    FormCard: typeof import('./src/components/common/FormCard.vue')['default']
    FormTitle: typeof import('./src/components/common/FormTitle.vue')['default']
    Line: typeof import('./src/components/common/Line.vue')['default']
    LoopOperation: typeof import('./src/components/common/LoopOperation.vue')['default']
    MInput: typeof import('./src/components/antd/MInput.vue')['default']
    MInputInner: typeof import('./src/components/antd/MInputInner.vue')['default']
    MSelect: typeof import('./src/components/antd/MSelect.vue')['default']
    NormalSelect: typeof import('./src/components/common/NormalSelect.vue')['default']
    Operation: typeof import('./src/components/common/Operation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./src/components/common/TaskCard.vue')['default']
    TimePicker: typeof import('./src/components/common/TimePicker.vue')['default']
    TimeSelect: typeof import('./src/components/common/TimeSelect.vue')['default']
    TimingOperation: typeof import('./src/components/common/TimingOperation.vue')['default']
    TitleAuto: typeof import('./src/components/common/TitleAuto.vue')['default']
    TitleAutoInfo: typeof import('./src/components/common/TitleAutoInfo.vue')['default']
    VanDatetimeP: typeof import('vant/es')['DatetimeP']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanPicker: typeof import('vant/es')['Picker']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    WarningCard: typeof import('./src/components/common/WarningCard.vue')['default']
  }
}
